### ISSUE TITLE
Fix load more issue in mentors list

### ISSUE THREAD

**Issue by elangosundar** [10secondsofcode/coding-ai#110]
1. Initially we will display the 12 mentors in initial load.
2. When we cLick the load more button , will load the next 12 mentors list, continues ly .

**Comment by hwindo** [comment]
Hi @elangovanshanthi, can I work on this

**Comment by hwindo** [comment]
Please kindly review the PR #112 👍🏼

**Comment by 10-seconds** [comment]
> Please kindly review the PR #112 👍🏼

Thanks for your help

**Comment by hwindo** [comment]
> > Please kindly review the PR #112 👍🏼
> 
> Thanks for your help

Thanks!
