### ISSUE TITLE
create login popup component

### ISSUE THREAD

**Issue by 10-seconds** [10secondsofcode/coding-ai#119]
create login popup component

**Comment by arteevraina** [comment]
I would like to work on this issue but can you explain me in detail what kind of login popup you want?

**Comment by 10-seconds** [comment]
@arteevraina already we have login component. so we can utlize and will create the login popup component and you will select any popup component, but makes sense.

**Comment by valerio-pizzichini** [comment]
Hi, developed the login popup component but cant push due to permission error. 
Any tips to push and make a pull request?

**Comment by elangosundar** [comment]
@sf3ris Did you fork this https://github.com/10secondsofcode/coding-ai repo and you will added your changes and will create the PR from Your repo to coding-ai repo.

**Comment by valerio-pizzichini** [comment]
@elangovanshanthi, cloned the repository instead forking it.
Going to fork and apply those changes already done as soon as i got home. 
Thanks.

**Comment by myungwoo-Y** [comment]
I would like to work on this issue . Can I take this issue?

**Comment by elangosundar** [comment]
> I would like to work on this issue . Can I take this issue?

sure @myungwoo-Y
