### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by 10-seconds** [10secondsofcode/coding-ai#15]
1. Improve the UI items for menus, search bar and mentorlist card.
2. Make Mentor's photos as rounded circle of displaying images and below will show the mentors info.

**Comment by ethanmassie** [comment]
Can I help with this one?

**Comment by 10-seconds** [comment]
sure @ethanmassie

**Comment by zarasyversen** [comment]
Could I help as well by fixing the mobile menu toggle? Maybe make it a sidebar as well instead of dropping down on the page. @ethanmassie are you fixing the mobile menu?

**Comment by ethanmassie** [comment]
You can take that part @zarasyversen I'll do the rounded photos
