### ISSUE TITLE
Fix the react router issue 

### ISSUE THREAD

**Issue by elangosundar** [10secondsofcode/coding-ai#30]
When navigating to mentors detailed list page and refresh the page, it will throwing 404 page. Anyone will fix this issue?

**Comment by CSBatchelor** [comment]
I'll do this one.

**Comment by elangosundar** [comment]
@CSBatchelor thanks...

**Comment by muhammadsumair** [comment]
@elangovanshanthi there is no route for mentors detailed list page

**Comment by atultherajput** [comment]
@elangovanshanthi Please elaborate on this issue.

**Comment by consciousnessdev** [comment]
i'll take this
