### ISSUE TITLE
Create simple nodejs api for mentors list

### ISSUE THREAD

**Issue by elangosundar** [10secondsofcode/coding-ai#31]
1. Create simple nodejs api for mentorslist
2. It will handle menters CRUD operations
3. We will use api in coding-ai for mentors list.

**Comment by mohammadsadeghforoughi** [comment]
where I can do that?

**Comment by elangosundar** [comment]
@mohammadsadeghforoughi Coding-ai itself . Create api folder inside coding-ai. ...

**Comment by rmasianjr** [comment]
Hi, i want to help. :relaxed: 
question...
1. do we need to store it in database or in a simple array?
2. shape of mentor's data? (ex. {name: 'string', language: 'string', .....}).
Thanks.. :)

**Comment by elangosundar** [comment]
Anyone have idea , how to deploy nodejs app in api folder in netlify

**Comment by mashiromashi** [comment]
@elangovanshanthi you might wanna use Heroku rather than netlify

**Comment by elangosundar** [comment]
> @elangovanshanthi you might wanna use Heroku rather than netlify
@mashiromashi For nodejs api alone right?

**Comment by mashiromashi** [comment]
@elangovanshanthi yes for the backend. Netlify is good for frontend only as far as i know.

**Comment by elangosundar** [comment]
@mashiromashi  sure, i will move the api repo into heroku.

**Comment by niyoceles** [comment]
@elangovanshanthi I would like to add a contribution to this project on the Nodejs API for mentors:
> 1. Create simple nodejs api for mentorslist
> 2. It will handle menters CRUD operations
> 3. We will use api in coding-ai for mentors list

**Comment by elangosundar** [comment]
@niyoceles sure

**Comment by niyoceles** [comment]
> @niyoceles sure
You are welcome @elangovanshanthi.

**Comment by niyoceles** [comment]
Hi @elangovanshanthi ;

I am about to finish this Nodejs API for mentors. As far as I have been working on my repo: [https://github.com/niyoceles/coding-ai-api](https://github.com/niyoceles/coding-ai-api), So, I would like to get a repository for **Coding-ai API** HERE in 10secondsofcode.

**Comment by elangosundar** [comment]
@niyoceles thanks for your hard work and we will use this repo for coding-ai-api fo mentors and will create the pr for this repo
https://github.com/10secondsofcode/coding-ai-api.

I will create slack account and will join .

**Comment by niyoceles** [comment]
That sounds great.

**Comment by 10-seconds** [comment]
@here all are join our slack account

https://10secondsofcode.slack.com/

**Comment by elangosundar** [comment]
Thanks for your help to making the nodes API
