### ISSUE TITLE
Add translations file multiple countries

### ISSUE THREAD

**Issue by elangosundar** [10secondsofcode/coding-ai#47]
Add readme.md file for multiple countries language. It is located in translations folder.

**Comment by Moorad** [comment]
Hello! I can trasnslate it to Arabic.

**Comment by elangosundar** [comment]
> Hello! I can trasnslate it to Arabic.

Sure @mooradal

**Comment by tloth** [comment]
I'll take Hungarian!

**Comment by elangosundar** [comment]
> I'll take Hungarian!

Sure @tloth

**Comment by adinalini** [comment]
I'll take Hindi

**Comment by elangosundar** [comment]
> I'll take Hindi

Sure @adinalini

**Comment by nickjlee** [comment]
I can translate to Korean

**Comment by tloth** [comment]
submitted a PR :)

**Comment by sajjadtaghilou** [comment]
I can translate it to Persia

**Comment by sittichoke** [comment]
I can translate to Thai.

**Comment by elangosundar** [comment]
> I can translate to Thai.

sure @sittichoke

**Comment by nickjlee** [comment]
made a PR for korean translation

**Comment by thecodekaizen** [comment]
made a PR for hindi translation

**Comment by manikkalai-kannan** [comment]
I can translate to Tamil.

**Comment by HarisSpahija** [comment]
I can translate to Dutch!

**Comment by drunkedMonkey** [comment]
I can translate to Spanish, from Spain.

**Comment by Nicklaspoke** [comment]
made a PR for swedish translation #66
