### ISSUE TITLE
Coding AI apps is not loading 

### ISSUE THREAD

**Issue by elangosundar** [10secondsofcode/coding-ai#63]
Coding AI mentors app is not loading properly., Due to filters js throwing some error. Anyone looking on this? 
Volunteer s are welcome...! 
Sorry Now i am in journey....?!

**Comment by HarisSpahija** [comment]
Hi @elangovanshanthi , I will look into this. Can you explain your steps to reproduce the error?

**Comment by gerlis18** [comment]
Fixed in #64

**Comment by elangosundar** [comment]
@gerlis18 thanks fo your help.   Perfect 👌
