### ISSUE TITLE
 Hosted https://mentors.netlify.com/  has error in <Filter> component

### ISSUE THREAD

**Issue by emmbyiringiro** [10secondsofcode/coding-ai#68]
![crash](https://user-images.githubusercontent.com/46843540/67132687-d2fe0100-f209-11e9-8ad3-93cdb1a0c062.PNG)

Here pull request for fix.
#69

**Comment by s0meon3** [comment]
I can work on this :)

**Comment by emmbyiringiro** [comment]
I have fix this one I 'm gonna sent Pull Request
![life](https://user-images.githubusercontent.com/46843540/67132873-8ebf3080-f20a-11e9-8660-392079e25b3e.PNG)

**Comment by s0meon3** [comment]
oh, ok then
